"""empty message

Revision ID: 95eb5e161968
Revises: 3a19541f0ef6
Create Date: 2021-11-03 17:56:38.510617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95eb5e161968'
down_revision = '3a19541f0ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_genres',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_genres')
    # ### end Alembic commands ###
